# Generated by Django 2.1.4 on 2018-12-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='book_images/%Y/%m/%d/'),
        ),
    ]
