# Generated by Django 2.1.4 on 2018-12-07 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_author_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='picture',
            new_name='author_profile_picture',
        ),
    ]
