# Generated by Django 2.1.4 on 2018-12-12 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20181211_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': (('can_create_author', 'Create new author'), ('can_update_author', 'Update author details'), ('can_delete_author', 'Delete author'))},
        ),
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
