# Generated by Django 2.1.4 on 2018-12-12 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20181212_0941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'), ('can_create_book', 'Create new book'), ('can_update_book', 'Update book details'), ('can_delete_book', 'Delete book'))},
        ),
    ]
