# Generated by Django 2.1.4 on 2018-12-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20181212_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='imprint',
        ),
        migrations.AlterField(
            model_name='author',
            name='author_profile_picture',
            field=models.ImageField(blank=True, default='author_images/no_image.png', null=True, upload_to='author_images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, default='book_pdf/no_pdf.pdf', null=True, upload_to='book_pdf/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(blank=True, default='book_images/no_profile_picture.png', null=True, upload_to='book_images/%Y/%m/%d/'),
        ),
    ]
